version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "8080:8080"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
